-- MySQL Script generated by MySQL Workbench
-- 06/24/16 00:07:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema handshake
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema handshake
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `handshake` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `handshake` ;

-- -----------------------------------------------------
-- Table `handshake`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `handshake`.`Groups` (
  `group_id` BIGINT(20) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`group_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
