-- MySQL Script generated by MySQL Workbench
-- 06/25/16 00:10:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema handshake
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema handshake
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `handshake` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `handshake` ;

-- -----------------------------------------------------
-- Table `handshake`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `handshake`.`Groups` (
  `groupId` BIGINT(20) NOT NULL COMMENT '',
  `groupname` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`groupId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `handshake`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `handshake`.`Users` (
  `userId` BIGINT(20) NOT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`userId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `handshake`.`GroupsHasUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `handshake`.`GroupsHasUsers` (
  `groupId` BIGINT(20) NOT NULL COMMENT '',
  `userId` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`groupId`, `userId`)  COMMENT '',
  INDEX `fk_Groups_has_Users_Users1_idx` (`userId` ASC)  COMMENT '',
  INDEX `fk_Groups_has_Users_Groups_idx` (`groupId` ASC)  COMMENT '',
  CONSTRAINT `fk_Groups_has_Users_Groups`
    FOREIGN KEY (`groupId`)
    REFERENCES `handshake`.`Groups` (`groupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Groups_has_Users_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `handshake`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;